FROM node:latest

WORKDIR /app

COPY . .

ENV NODE_ENV=container

# Provide your own token and database details on the lines below:

ENV TOKEN=

ENV DB_NAME=

ENV DB_PORT=

RUN npm install

CMD [ "npm", "start" ]